version: 0.2

phases:
  pre_build:
    commands:
      # Added quotes below to fix the error
      - echo "Logging in to Amazon ECR (Mumbai)..."
      - aws ecr get-login-password --region ap-south-1 | docker login --username AWS --password-stdin 878796851842.dkr.ecr.ap-south-1.amazonaws.com
      
      - REPOSITORY_URI=878796851842.dkr.ecr.ap-south-1.amazonaws.com/weather-app-repo
      - COMMIT_HASH=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7)
      - IMAGE_TAG=${COMMIT_HASH:=latest}

  build:
    commands:
      - echo "Build started on $(date)"
      - echo "Building the Docker image..."
      - docker build -t $REPOSITORY_URI:latest .
      - docker tag $REPOSITORY_URI:latest $REPOSITORY_URI:$IMAGE_TAG

  post_build:
    commands:
      - echo "Build completed on $(date)"
      - echo "Pushing the Docker images to ECR..."
      - docker push $REPOSITORY_URI:latest
      - docker push $REPOSITORY_URI:$IMAGE_TAG
      
      - echo "Updating Lambda function in Mumbai..."
      - aws lambda update-function-code --region ap-south-1 --function-name weather-app-lambda --image-uri $REPOSITORY_URI:latest